### ISSUE TITLE
Problem: import-export simulation tests fails with different global account numbers

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/chain-main#53]
the test can be executed with `runsim -Jobs=4 -SimAppPkg=github.com/crypto-com/chain-main/app 25 5 TestAppImportExport` (runsim can be installed with `GO111MODULE="on" go get github.com/cosmos/tools/cmd/runsim@v1.0.0`)

it runs a randomised simulation and then tries to re-play it and check if the end-state is the same.

when it fails, it also shows how it can be reproduced:
```
go test github.com/crypto-com/chain-main/app -run TestAppImportExport -Enabled=true -NumBlocks=25 -Genesis= -Verbose=true -Commit=true -Seed=2 -Period=5 -ExportParamsPath ... -ExportStatePath ... -v -timeout 24h
```

The end "state" seems to be correct, except all account numbers and "global account number" are off by two:

```
...
                                address: cosmos1lakqt34l4244pph3jh2t0v96h5rd8d26g77kp0
                                coins:
                                - denom: stake
                                  amount: "366772073"
                                public_key: cosmospub1addwnpepqf487zy0e3fw7gtjayxpl2h3ffkgyyq2dmvc69ttq2h22ukhs05m55akjtc
                                account_number: 448
                                sequence: 8
                                original_vesting:
                                - denom: stake
                                  amount: "90270376125"
                                delegated_free:
                                - denom: stake
                                  amount: "473658128"
                                delegated_vesting: []
                                end_time: 6118429836
                                start_time: 6118410877
                            
                                address: cosmos1lakqt34l4244pph3jh2t0v96h5rd8d26g77kp0
                                coins:
                                - denom: stake
                                  amount: "366772073"
                                public_key: cosmospub1addwnpepqf487zy0e3fw7gtjayxpl2h3ffkgyyq2dmvc69ttq2h22ukhs05m55akjtc
                                account_number: 450
                                sequence: 8
                                original_vesting:
                                - denom: stake
                                  amount: "90270376125"
                                delegated_free:
                                - denom: stake
                                  amount: "473658128"
                                delegated_vesting: []
                                end_time: 6118429836
                                start_time: 6118410877
                                GlobalAccNumberA: 516
                                GlobalAccNumberB: 518
--- FAIL: TestAppImportExport (34.02s)
```
